num_runs: 500
num_repeat_interleaving: 500
result_length: 10
verbose: false
num_relevant: 1-3
experimenter: experiment.VASyntheticComparisonExperiment

rankings: "synthetic"
verticals: "News"
vertical_posmethod: beyondten

run_start_id: 0
processes: 24
output_prefix: synthetic-RQ2-pareto-1vert

# FEDERATED
user_model: environment.FederatedClickModel
user_model_args: "0.2 0.1"

# RANDOM
#user_model: environment.RandomClickModel
#user_model_args: 0.5

offline_metrics: ""
compute_online_metrics: false
compute_interleaved_metrics: false

system_comparison: "pareto"
# model to determine pareto-dominance
pareto_um_class: environment.FederatedClickModel
pareto_um_args: "0.2 0.1"

# method names have to be unique
evaluation_methods:

- TDI
- VA-TDI
- OI
- VA-OI


evaluation_methods_args:

- "--class_name comparison.TeamDraft"

- "--class_name comparison.VaTdi --aggregate expectation --compare_td 1"

- "--class_name comparison.OptimizedInterleave --ranker det --ranker_args None --aggregate expectation --compare_td 1 -c linear_credit"

- "--class_name comparison.OptimizedInterleaveVa --ranker det --ranker_args None --aggregate expectation --compare_td 1 -c linear_credit"

